### ISSUE TITLE
Take and Hold Scoreboard Disabler

### ISSUE THREAD

**Issue by ash-hat** [Deli-Collective/Deli.H3VR#4]
Many mods patch the Take and Hold scoring system. More specifically, a lot of them patch the method that submits scores to the Steam leaderboards to prevent modded scores from leaking to public leaderboards. This patching could be centralized to Deli.H3VR.

**Comment by nrgill28** [comment]
To add on to this; I feel it makes more sense to patch the steamworks methods directly so any form of leaderboard submission is disabled.

**Comment by Frityet** [comment]
As a suggestion, maybe an alternative database for leaderboards that are modded?

**Comment by nrgill28** [comment]
I don't want to say something like that _won't_ be in Deli.H3VR because I think something like that should be provided by standard if it exists, however the logistics of that would surely be a handful. Who is going to host and pay for it? Do you trust them to not collect the IP address or other data of every player who plays TNH modded? Would you separate leaderboards based on what mods people have installed? etc. etc.

All forms of Steam leaderboard uploading will be disabled in the next release so closing this issue.
