### ISSUE TITLE
Object oriented custom panel framework

### ISSUE THREAD

**Issue by Frityet** [Deli-Collective/Deli.H3VR#5]
This would be an extension to the API which would allow for an object oriented approach towards creating custom panels, such as the old H3MP panel that was unused, or the ItemSpawner panel. 

I envision the framework to be a Widget-GUI based design, where objects are added programmatically to the panel, much as how the UnityEditor approaches Editor UI design.

First, we have the base abstract class for the panel, which will provide any implementors with the requirements of making a new panel.
Some properties might be

- Colour
- Size
- Mobility (for panels meant to be immobile, such as ones used in maps)
- Array of "widgets" to be displayed on the panel

Finally, a function must be present which actually "spawns" the panel (this is so while the actual object of the panel may be created earlier, the object in game could be spawned by say, a menu item)

Note: this is my first time doing a improvement issue on a project like this, pls give feedback

**Comment by nrgill28** [comment]
The widgets are similar to what I already have planned. It sounds like you're requesting WPF style UI building, however that would not be practical in Unity, even less so in Unity 5.6. Instead [it will take the form of a builder / configurator](https://gist.github.com/nrgill28/88dd37031a25079d53e53f4ca6425bc9) which is a very clean pattern once you learn what it all does.

For the lockable panel; I do think it would be a good idea to have a wrapper class that handles the creation and management of the panel, however it would not be abstract and all it would really do is just abstract away the whole "did Unity destroy this and do I have to make a new one again" part along with the process for making a new one into just a single method call to get the panel game object.

Configuring this wrapper class with the widgets you want to have on the panel will be there of course. The color of the panel is something I have already looked into and the nuance here is that the color is actually coming right from the texture for the panel and isn't defined in a material or somewhere it is easily changeable. I think the best option for this is to just allow the mod to override the panel's texture with their own instead of trying to do hue shifting on textures at runtime. Size is easily done by just scaling the game object so that's a non-issue, and although I don't think adding code for "mobility" in Deli.H3VR is necessary the panel configuration class should allow you to accomplish something like that too.

So overall, yes these are things which I've already got planned. I may break this issue apart into two smaller ones later for the widgets and the panel class since they are both large enough features.

**Comment by nrgill28** [comment]
The wrapper class and panel textures were implemented in [Deli.H3VR v0.1.1](https://github.com/Deli-Collective/Deli.H3VR/releases/tag/v0.1.1). I will close this issue and make a new one specifically for widgets since that is a much larger task.
